### PR TITLE
Add :compojure/route-context to the request map

### PR DESCRIPTION
**Pull request by liamchzh**
Contains the combined route context for the current route.

Relates to #210.

### CODE REVIEW

**Comment by weavejester** [comment]
Can you change the commit message to:

```
Add :compojure/route-context to the request map

Contains the combined route context for the current route.
```

**Comment by liamchzh** [comment]
> Can you change the commit message to:
> 
> ```
> Add :compojure/route-context to the request map
> 
> Contains the combined route context for the current route.
> ```

The commit message has been updated.

**Comment by liamchzh** [comment]
@weavejester Hi James, sorry for pestering you again, could you push a new release when you have a chance?

**Comment by weavejester** [comment]
Released 1.7.0.

**Pull request merged**
