### PR TITLE
Extend `IPersistentMap` instead of `APersistentMap`

### LINKED ISSUE #159: Renderable extends `APersistentMap` and not `IPersistentMap`
This means that things which are implementations of Clojure-compatible maps (such as https://github.com/ztellman/aleph/blob/master/src/aleph/http/core.clj#L207) will not be recognized as a valid response, as reported here: https://github.com/ztellman/aleph/issues/298.

I understand that by extending an interface over a protocol you risk intersecting implementations, but I'd argue the same is true for an abstract class.

### PR DESCRIPTION
**Pull request by xiongtx**
Fixes #159.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks. Can you change the commit message to:

    Change Renderable to extend IPersistentMap

    Fixes #159.

**Comment by xiongtx** [comment]
Done.

**Comment by weavejester** [comment]
The commit message isn't quite right. The backticks need to be removed (it's not markdown after all), and "See" needs to be "Fixes" so it describes that it's fixing issue #159 rather than is just related to it.

Basically make it follow the same standard as the other commits in the repository. 😃

**Comment by xiongtx** [comment]
OK. I thought `Fixes` causes GitHub to automatically close the issue, and I don't like to close issues until the maintainer has verified that they're fixed.

**Comment by weavejester** [comment]
It does close the issue, but if I merge the PR then I've effectively verified the issue is fixed and should be closed anyway.

**Pull request merged**
