### PR TITLE
Add middleware for handling trailing slashes

### PR DESCRIPTION
**Pull request by Christopher-Bui**
I wasn't sure where to put the middleware so I made a ns for it. Feedback please.

Issue: https://github.com/weavejester/compojure/issues/68

### CODE REVIEW

**Comment by Christopher-Bui** [comment]
Ping @weavejester

**Comment by weavejester** [comment]
This wasn't *quite* what I had in mind, but it's not too far off.

First, we need to think a little about efficiency. You can use seq functions (like `butlast` etc) on strings, but they're orders of magnitude slower than just using the native methods on the string. So:

```clojure
(defn remove-last-character [^String s]
  (.substring s (dec (.length s))))
```

The above code is around 300x faster than your function that uses `apply str` and `butlast`. Likewise:

```clojure
(defn trailing-slash? [^String s]
  (.endsWith s "/"))
```

Again, a speedup of around 200x.

Next, you have two middleware functions, but I don't think it makes sense to split them up as part of the public API. Instead, you could write something like:

```clojure
(defn wrap-remove-trailing-slash [handler]
  (fn [{uri :uri :as request}]
    (if (trailing-slash? uri)
      (let [handler (wrap-routes handler wrap-redirect-to-canonical)]
        (handler (assoc request :uri (remove-last-character uri) ::slash-removed? true))))
      (handler request))))
```

So now people just need to use the outer middleware function, and it'll automatically wrap the inner one.

Now we're doing everything in one function, I don't think we actually need a custom key in the request map, since we can use closures instead. In fact, the inner middleware barely needs to do anything at all, it just needs to redirect only if the route matches. So we can write:

```clojure
(defn wrap-remove-trailing-slash [handler]
  (fn [{uri :uri :as request}]
    (if (trailing-slash? uri)
      (let [uri (remove-last-character uri)
            handler (wrap-routes handler (constantly (resp/redirect uri 301)))]
        (handler (assoc request :uri uri))
      (handler request))))
```

I also think we can be a little more general in our approach. Let's say we have a function that turns a non-canonical url into a canonical one. If the URIs are different, we redirect, otherwise we pass on to the handler:

```clojure
(defn wrap-canonical-redirect [handler make-canonical]
  (fn [{uri :uri :as request}]
    (let [canonical (make-canonical uri)]
      (if (= canonical uri)
        (handler request)
        (let [handler (wrap-routes handler (constantly (resp/redirect canonical 301)))]
          (handler (assoc request :uri canonical)))))))
```

Then maybe we expose a function like:

```clojure
(defn remove-trailing-slash [^String uri]
  (if (.endsWith uri "/")
    (.substring uri (dec (.length uri)))
    uri))
```

And make it the default argument.

**Comment by weavejester** [comment]
Did you get my response, @Christopher-Bui?

**Comment by Christopher-Bui** [comment]
Yup, been busy.

**Comment by Christopher-Bui** [comment]
Been a while, ping @weavejester

**Comment by weavejester** [comment]
You've implemented some of the changes I suggested, but you haven't implemented the others. You don't have `wrap-routes` anywhere in your codebase, so it won't fall through if no routes match, and you haven't put in a default argument.

**Comment by Christopher-Bui** [comment]
Ok. I did this a while back and had some issues with wrap-routes if I recall. I'll give it another go.

**Comment by weavejester** [comment]
Take a look at the examples I put in my first response. Though now that I think about it, it might be more performant to place the `wrap-routes` code outside the handler function. So something like:

```clojure
(defn wrap-canonical-redirect
  ([handler]
   (wrap-canonical-redirect handler remove-trailing-slash))
  ([handler make-canonical]
   (let [redirect-handler (wrap-routes handler (constantly #(resp/redirect (:uri %) 301)]
     (fn [{uri :uri :as request}]
       (let [canonical (make-canonical uri)]
         (if (= uri canonical)
           (handler request)
           (redirect-handler (assoc request :uri canonical))))))))
```

Without `wrap-routes`, the middleware can't know for certain whether or not the routes inside the handler have matched or not. So when we want to redirect, we don't return a response directly, but instead use `wrap-routes` to inject the redirect response into the routes.

**Pull request closed without merging**
